### ISSUE TITLE
crash if used with Geyser

### ISSUE THREAD

**Issue by flabbierduck435** [PigCart/dedicatedmcupnp#6]
the server will run with both on there own but will crash if both are used at the same time

```
[19:39:48] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.7
[19:39:48] [main/INFO]: Loading 76 mods:
	- dedicatedmcupnp 1.2.3
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- geyser-fabric 2.2.2-SNAPSHOT
	   |-- com_fasterxml_jackson_core_jackson-annotations 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-core 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-databind 2.17.0
	   |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.17.0
	   |-- com_github_steveice10_opennbt 1.6
	   |-- com_nukkitx_natives 1.0.3
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- io_airlift_aircompressor 0.25
	   |-- net_bytebuddy_byte-buddy 1.14.9
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_kyori_adventure-api 4.15.0
	   |-- net_kyori_adventure-key 4.15.0
	   |-- net_kyori_adventure-nbt 4.15.0
	   |-- net_kyori_adventure-text-serializer-gson 4.15.0
	   |-- net_kyori_adventure-text-serializer-json 4.15.0
	   |-- net_kyori_adventure-text-serializer-json-legacy-impl 4.15.0
	   |-- net_kyori_adventure-text-serializer-legacy 4.15.0
	   |-- net_kyori_adventure-text-serializer-plain 4.15.0
	   |-- net_kyori_examination-api 1.3.0
	   |-- net_kyori_examination-string 1.3.0
	   |-- net_kyori_option 1.0.0
	   |-- org_bitbucket_b_c_jose4j 0.9.3
	   |-- org_cloudburstmc_block-state-updater 1.20.70-20240303.125052-2
	   |-- org_cloudburstmc_math_api 2.0
	   |-- org_cloudburstmc_math_immutable 2.0
	   |-- org_geysermc_api_base-api 1.0.0-SNAPSHOT
	   |-- org_geysermc_cumulus_cumulus 1.1.2
	   |-- org_geysermc_event_events 1.1-SNAPSHOT
	   |-- org_geysermc_geyser_common 2.2.2-SNAPSHOT
	   |-- org_java-websocket_java-websocket 1.5.1
	   |-- org_lanternpowered_lmbda 2.0.0
	   \-- org_yaml_snakeyaml 2.2
	- java 22
	- minecraft 1.20.4
[19:39:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/carte/AppData/Roaming/com.modrinth.theseus/profiles/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[19:39:48] [main/INFO]: Compatibility level set to JAVA_17
[19:39:48] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[19:39:56] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geyser-fabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader, org.yaml.snakeyaml.LoaderOptions)'
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:204) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:505) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:393) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3713) ~[com_fasterxml_jackson_core_jacksbind-2.17.0-a77f5dd3a784b4a0.jar:?]
	at org.geysermc.geyser.util.FileUtils.loadConfig(FileUtils.java:60) ~[geyser-fabric-2.2.2-SNAPSHOT+build.474.jar:?]
	at org.geysermc.geyser.platform.mod.GeyserModBootstrap.loadConfig(GeyserModBootstrap.java:273) ~[geyser-fabric-2.2.2-SNAPSHOT+build.474.jar:?]
	at org.geysermc.geyser.platform.mod.GeyserModBootstrap.onGeyserInitialize(GeyserModBootstrap.java:91) ~[geyser-fabric-2.2.2-SNAPSHOT+build.474.jar:?]
	at org.geysermc.geyser.platform.fabric.GeyserFabricBootstrap.onInitialize(GeyserFabricBootstrap.java:60) ~[geyser-fabric-2.2.2-SNAPSHOT+build.474.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	... 6 more
```

**Comment by flabbierduck435** [comment]
i think fix somewhat i am 1.20..4 butt tried the 1.19 version of the mod it loads and shows it starting in the log but have not tested it so not sure if it is fully working

**Comment by flabbierduck435** [comment]
ok it don't work the server just crash if you try to run the upnp command but is says that they are opening and closing in chat. also i cant connect to the server

**Comment by flabbierduck435** [comment]
not sure if it will help with fixing this but here it is on another pc with less mods on
`Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:39:19] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.9
[13:39:19] [main/INFO]: Loading 81 mods:
        - dedicatedmcupnp 1.2.3
        - fabric-api 0.96.11+1.20.4
           |-- fabric-api-base 0.4.36+78d798af4f
           |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
           |-- fabric-biome-api-v1 13.0.16+78d798af4f
           |-- fabric-block-api-v1 1.0.16+3e2216cb4f
           |-- fabric-block-view-api-v2 1.0.4+78d798af4f
           |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
           |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
           |-- fabric-command-api-v1 1.2.41+f71b366f4f
           |-- fabric-command-api-v2 2.2.20+78d798af4f
           |-- fabric-commands-v0 0.2.58+df3654b34f
           |-- fabric-containers-v0 0.1.86+df3654b34f
           |-- fabric-content-registries-v0 5.0.15+78d798af4f
           |-- fabric-convention-tags-v1 1.5.10+78d798af4f
           |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
           |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
           |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
           |-- fabric-dimensions-v1 2.1.61+78d798af4f
           |-- fabric-entity-events-v1 1.6.1+09fc25014f
           |-- fabric-events-interaction-v0 0.7.1+389931eb4f
           |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
           |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
           |-- fabric-item-api-v1 2.2.0+d6f2b0844f
           |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
           |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
           |-- fabric-keybindings-v0 0.2.39+df3654b34f
           |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
           |-- fabric-loot-api-v2 2.1.9+78d798af4f
           |-- fabric-message-api-v1 6.0.5+78d798af4f
           |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
           |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
           |-- fabric-models-v0 0.4.7+9386d8a74f
           |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
           |-- fabric-object-builder-api-v1 13.0.14+080016e44f
           |-- fabric-particles-v1 1.1.7+78d798af4f
           |-- fabric-recipe-api-v1 2.0.20+78d798af4f
           |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
           |-- fabric-renderer-api-v1 3.2.4+78d798af4f
           |-- fabric-renderer-indigo 1.5.4+78d798af4f
           |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
           |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
           |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
           |-- fabric-rendering-v0 1.1.56+df3654b34f
           |-- fabric-rendering-v1 3.2.0+6fd945a04f
           |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
           |-- fabric-resource-loader-v0 0.11.20+df798a894f
           |-- fabric-screen-api-v1 2.0.17+78d798af4f
           |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
           |-- fabric-sound-api-v1 1.0.17+78d798af4f
           |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
           \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
        - fabricloader 0.15.9
           \-- mixinextras 0.3.5
        - floodgate 2.2.0-SNAPSHOT
           \-- cloud 1.8.4
                |-- cloud_commandframework_cloud-brigadier_ 1.8.4
                |-- cloud_commandframework_cloud-core_ 1.8.4
                |-- cloud_commandframework_cloud-services_ 1.8.4
                |-- fabric-permissions-api-v0 0.2-SNAPSHOT
                \-- io_leangen_geantyref_geantyref 1.3.13
        - geyser-fabric 2.2.3-SNAPSHOT
           |-- com_fasterxml_jackson_core_jackson-annotations 2.17.0
           |-- com_fasterxml_jackson_core_jackson-core 2.17.0
           |-- com_fasterxml_jackson_core_jackson-databind 2.17.0
           |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.17.0
           |-- com_github_steveice10_opennbt 1.6
           |-- com_nukkitx_natives 1.0.3
           |-- fabric-permissions-api-v0 0.2-SNAPSHOT
           |-- io_airlift_aircompressor 0.25
           |-- net_bytebuddy_byte-buddy 1.14.9
           |-- net_jodah_expiringmap 0.5.10
           |-- net_kyori_adventure-api 4.15.0
           |-- net_kyori_adventure-key 4.15.0
           |-- net_kyori_adventure-nbt 4.15.0
           |-- net_kyori_adventure-text-serializer-gson 4.15.0
           |-- net_kyori_adventure-text-serializer-json 4.15.0
           |-- net_kyori_adventure-text-serializer-json-legacy-impl 4.15.0
           |-- net_kyori_adventure-text-serializer-legacy 4.15.0
           |-- net_kyori_adventure-text-serializer-plain 4.15.0
           |-- net_kyori_examination-api 1.3.0
           |-- net_kyori_examination-string 1.3.0
           |-- net_kyori_option 1.0.0
           |-- org_bitbucket_b_c_jose4j 0.9.3
           |-- org_cloudburstmc_block-state-updater 1.20.70-20240303.125052-2
           |-- org_cloudburstmc_math_api 2.0
           |-- org_cloudburstmc_math_immutable 2.0
           |-- org_geysermc_api_base-api 1.0.0-SNAPSHOT
           |-- org_geysermc_cumulus_cumulus 1.1.2
           |-- org_geysermc_event_events 1.1-SNAPSHOT
           |-- org_java-websocket_java-websocket 1.5.1
           |-- org_lanternpowered_lmbda 2.0.0
           \-- org_yaml_snakeyaml 2.2
        - java 22
        - minecraft 1.20.4
[13:39:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/RaccoonServer/AppData/Roaming/com.modrinth.theseus/profiles/server%201.0.0/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[13:39:19] [main/INFO]: Compatibility level set to JAVA_17
[13:39:20] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[13:39:30] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'geyser-fabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.9.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader, org.yaml.snakeyaml.LoaderOptions)'
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:204) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:505) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:393) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[com_fasterxml_jackson_dataformatyaml-2.17.0-112d828b9ddfab37.jar:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3713) ~[com_fasterxml_jackson_core_jacksbind-2.17.0-a77f5dd3a784b4a0.jar:?]
        at org.geysermc.geyser.util.FileUtils.loadConfig(FileUtils.java:63) ~[geyser-fabric-2.2.3-SNAPSHOT+build.485.jar:?]
        at org.geysermc.geyser.platform.mod.GeyserModBootstrap.loadConfig(GeyserModBootstrap.java:273) ~[geyser-fabric-2.2.3-SNAPSHOT+build.485.jar:?]
        at org.geysermc.geyser.platform.mod.GeyserModBootstrap.onGeyserInitialize(GeyserModBootstrap.java:91) ~[geyser-fabric-2.2.3-SNAPSHOT+build.485.jar:?]
        at org.geysermc.geyser.platform.fabric.GeyserFabricBootstrap.onInitialize(GeyserFabricBootstrap.java:60) ~[geyser-fabric-2.2.3-SNAPSHOT+build.485.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.9.jar:?]
        ... 6 more`

**Comment by PigCart** [comment]
geyser is accessing some library embedded in my mod instead of the version embedded in geyser. not sure why that is happenening but i updated the library to the version geyser is trying to use as a temporary fix until i rework the config. try [v2.0.1](https://modrinth.com/mod/dedicatedmcupnp/version/2.0.1) and let me know if that works for you.

**Comment by flabbierduck435** [comment]
hello sorry i kind of forgot about this but i try and the server does not crash anymore but i cant seem to connect to server with it even with out geyser.

here is log but i dont think i will help much
`[14:39:02] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.10
[14:39:02] [main/INFO]: Loading 90 mods:
	- architectury 11.1.17
	- dedicatedmcupnp 2.0.1
	- fabric-api 0.97.0+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.62+78d798af4f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.5+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- floodgate 2.2.0-SNAPSHOT
	   \-- cloud 1.8.4
	        |-- cloud_commandframework_cloud-brigadier_ 1.8.4
	        |-- cloud_commandframework_cloud-core_ 1.8.4
	        |-- cloud_commandframework_cloud-services_ 1.8.4
	        \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- geyser-fabric 2.2.3-SNAPSHOT
	   |-- com_fasterxml_jackson_core_jackson-annotations 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-core 2.17.0
	   |-- com_fasterxml_jackson_core_jackson-databind 2.17.0
	   |-- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.17.0
	   |-- com_github_steveice10_opennbt 1.6
	   |-- com_nukkitx_natives 1.0.3
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- io_airlift_aircompressor 0.25
	   |-- io_netty_netty-codec-dns 4.1.107
	   |-- io_netty_netty-codec-haproxy 4.1.107
	   |-- io_netty_netty-resolver-dns-classes-macos 4.1.107
	   |-- net_bytebuddy_byte-buddy 1.14.9
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_kyori_adventure-api 4.15.0
	   |-- net_kyori_adventure-key 4.15.0
	   |-- net_kyori_adventure-nbt 4.15.0
	   |-- net_kyori_adventure-text-serializer-gson 4.15.0
	   |-- net_kyori_adventure-text-serializer-json 4.15.0
	   |-- net_kyori_adventure-text-serializer-json-legacy-impl 4.15.0
	   |-- net_kyori_adventure-text-serializer-legacy 4.15.0
	   |-- net_kyori_adventure-text-serializer-plain 4.15.0
	   |-- net_kyori_examination-api 1.3.0
	   |-- net_kyori_examination-string 1.3.0
	   |-- net_kyori_option 1.0.0
	   |-- org_bitbucket_b_c_jose4j 0.9.3
	   |-- org_cloudburstmc_block-state-updater 1.20.70-20240303.125052-2
	   |-- org_cloudburstmc_math_api 2.0
	   |-- org_cloudburstmc_math_immutable 2.0
	   |-- org_cloudburstmc_nbt 3.0.2
	   |-- org_geysermc_api_base-api 1.0.0-SNAPSHOT
	   |-- org_geysermc_cumulus_cumulus 1.1.2
	   |-- org_geysermc_event_events 1.1-SNAPSHOT
	   |-- org_java-websocket_java-websocket 1.5.1
	   |-- org_lanternpowered_lmbda 2.0.0
	   \-- org_yaml_snakeyaml 2.2
	- hurricane 1.0.2+1.20
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.14
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- java 22
	- minecraft 1.20.4
[14:39:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/carte/AppData/Roaming/com.modrinth.theseus/profiles/server/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:39:02] [main/INFO]: Compatibility level set to JAVA_16
[14:39:02] [main/INFO]: Compatibility level set to JAVA_17
[14:39:03] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[14:39:11] [main/INFO]: Loading extensions...
[14:39:11] [main/INFO]: Loaded 0 extension(s)
[14:39:11] [main/INFO]: Loading Hurricane
[14:39:11] [main/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:39:13] [main/INFO]: Loaded 7 recipes
[14:39:13] [main/INFO]: Loaded 1271 advancements
[14:39:14] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.619 ms
[14:39:14] [Server thread/INFO]: Starting minecraft server version 1.20.4
[14:39:14] [Server thread/INFO]: Loading properties
[14:39:14] [Server thread/INFO]: Default game type: SURVIVAL
[14:39:14] [Server thread/INFO]: Generating keypair
[14:39:14] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:39:14] [Server thread/INFO]: Using default channel type
[14:39:14] [Server thread/INFO]: Preparing level "world"
[14:39:15] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:39:17] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[14:39:17] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[14:39:17] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[14:39:17] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[14:39:17] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[14:39:18] [Worker-Main-7/INFO]: Preparing spawn area: 17%
[14:39:18] [Server thread/INFO]: Time elapsed: 2789 ms
[14:39:18] [Server thread/INFO]: Done (3.969s)! For help, type "help"
[14:39:18] [Server thread/INFO]: [STDOUT]: Attempting UPnP port forwarding...
[14:39:23] [Server thread/INFO]: [STDOUT]: UPnP opened TCP port 25565
[14:39:23] [Server thread/INFO]: Took 40ms to boot Floodgate
[14:39:23] [Server thread/INFO]: ******************************************
[14:39:23] [Server thread/INFO]: 
[14:39:23] [Server thread/INFO]: Loading Geyser version 2.2.3-SNAPSHOT (git-master-4d32b2f)
[14:39:23] [Server thread/INFO]: 
[14:39:23] [Server thread/INFO]: ******************************************
[14:39:27] [Server thread/INFO]: Started Geyser on 0.0.0.0:19132
[14:39:27] [Server thread/INFO]: Done (3.929s)! Run /geyser help for help!
[14:39:27] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8744ms or 174 ticks behind
`

**Comment by PigCart** [comment]
you need to add geysers port (UDP 19132) to the config to be able to connect from bedrock.
however unfortunately its common that it just doesn't work on some networks :(
